const data = [
  {
    name: "Tshirt one",
    slug: "tshirt-one",
    category: "Shirts",
    image: "/images/shirt1.jpg",
    price: 70,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    countInStock: 10,
    description: "made of cotton",
  },
  {
    name: "Tshirt two",
    slug: "tshirt-two",
    category: "Shirts",
    image: "/images/shirt2.jpg",
    price: 80,
    brand: "Puma",
    rating: 4,
    numReviews: 8,
    countInStock: 12,
    description: "made of cotton",
  },
  {
    name: "Tshirt three",
    slug: "tshirt-three",
    category: "Shirts",
    image: "/images/shirt3.jpg",
    price: 170,
    brand: "Gucci",
    rating: 4.9,
    numReviews: 15,
    countInStock: 4,
    description: "made of silk",
  },
  {
    name: "Jacket one",
    slug: "jacket-one",
    category: "Jackets",
    image: "/images/jacket1.jpg",
    price: 700,
    brand: "Gucci",
    rating: 5,
    numReviews: 10,
    countInStock: 10,
    description: "made of leather",
  },
  {
    name: "Pant one",
    slug: "pant-one",
    category: "Pants",
    image: "/images/pant1.jpg",
    price: 60,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    countInStock: 10,
    description: "made of cotton",
  },
  {
    name: "Sheath skirt one",
    slug: "Sheath-skirt one",
    category: "Skirts",
    image: "/images/skirt1.jpg",
    price: 55,
    brand: "adidas",
    rating: 3,
    numReviews: 15,
    countInStock: 8,
    description: "made of plastic",
  },
  {
    name: "Jacket two",
    slug: "jacket-two",
    category: "Jackets",
    image: "/images/jacket2.jpg",
    price: 90,
    brand: "Nike",
    rating: 4.7,
    numReviews: 10,
    countInStock: 10,
    description: "made of wool",
  },
  {
    name: "Pant two",
    slug: "pant-two",
    category: "Pants",
    image: "/images/pant2.jpg",
    price: 100,
    brand: "Zara",
    rating: 4.8,
    numReviews: 10,
    countInStock: 2,
    description: "made of cotton",
  },
  {
    name: "Shirt one",
    slug: "shirt-one",
    category: "Shirts",
    image: "/images/shirt4.jpg",
    price: 65,
    brand: "adidas",
    rating: 4.5,
    numReviews: 10,
    countInStock: 10,
    description: "made of thread",
  },
  {
    name: "Shirt two",
    slug: "shirt-two",
    category: "Shirts",
    image: "/images/shirt5.jpg",
    price: 40,
    brand: "Nike",
    rating: 4.5,
    numReviews: 20,
    countInStock: 2,
    description: "made of cotton",
  },
  {
    name: "Skirt one",
    slug: "skirt-one",
    category: "Skirts",
    image: "/images/skirt2.jpg",
    price: 95,
    brand: "Puma",
    rating: 4.5,
    numReviews: 10,
    countInStock: 10,
    description: "made of leather",
  },
];

export default data;
